config/routes.rb
Campus::Application.routes.draw do
  get "class_groups/index"

  get "class_groups/show"

  post "class_groups/create"

  get "class_groups/new"

  get "class_groups/edit"

  get "class_groups/update"

  get "class_groups/destroy"

  get "group/create"
  get "group/mygroup"
  get "lecture/mylecture"
  get "lecture/find_lecture"
 
 
  
  root :to => "homes#show"

  match '/majors' => 'majors#index'''
  match "/home/user_profile/id" =>'homes#user_profile'
  resources :courses do
    collection do
      get :school
    end
  end
 match 'home?' =>"class_group#create"
  match '/users/auth/:provider/callback' => 'authentications#create'  

  devise_for :users,:controllers=> {:sessions => 'sessions', :registrations=> 'registrations' }
  devise_scope :user do
    match '/users/registered' => 'registrations#registered'
  end
resources :courses do
  resources :class_group
    end
 match "/home/user_profile/:id" => 'homes#user_profile', :via=>:get
  resources :books do
    collection { get 'search' }
  end
  
  resources :lecture
  resource :lecture do
    collection do
      get 'mylecture'
      get 'find_lecture'
    end
  end

  resource :group do
    collection do
      get 'create'
      get 'mygroup'
    end
  end
  resources :posts do
    collection do
      get 'latest'
    end
  end

  namespace :setting do
    get "show"
    get "privacy"
    get "notification"
  end

 
  resource :home do
    member do
      get "profile"
      get "welcome"
      get "user_profile"
    end
  end
  
  resources :book_ownerships do
    member { post :reserve }
    collection { get :reserved }
  end

  resources :schools

  resource :requests do
    collection do
      get 'books'
      get 'messages'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_protected :user_id

  belongs_to :course
  belongs_to :user

  has_many :post_attachments

  has_many :replies, :class_name => 'Post', :foreign_key => :reply_id

=begin
  POST_TYPES = %w(help)
  belongs_to :post_type, :polymorphic => true
=end

  validates_presence_of :user_id, :course_id, :content

  scope :for_user, ->(user){ where(:course_id => user.course_ids) }
  scope :top_level, where(reply_id: nil)

  validate :valid_course_id, :if => :course_id

  after_create :set_course_ids

  def valid_course_id
    unless user.course_ids.include? course_id.to_i
      errors.add :course_id, "must be a course you are taking"
      return false
    end
  end

  # A post can be for multiple courses.
  # Rather than create a join table we duplicate the Post for each course.
  def set_course_ids
    return unless course_ids.present?

    (course_ids.map(&:to_i) - [course_id]).compact.each do |course_id|
      self.class.create attributes.merge(:course_id => course_id, :user => user, :attachment => attachment.try(:attachment))
    end
  end

  attr_accessor :course_ids

  def course_id= course_ids
    case course_ids
    when Array
      cids = course_ids.map {|cid| cid.to_i }.reject {|cid| cid == 0 }
      super(cids.shift).tap do
        self.course_ids = cids
      end
    else
      super course_ids
    end
  end

  def attachment= file
    return nil unless file
    post_attachments.build(:attachment => file)
  end

  def attachment
    post_attachments.first
  end

  def as_json options
    super(options.merge(:methods => [:attachment]))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :json
  respond_to :html, only: :create

  def index
    posts = get_posts
    respond_with make_json_tree posts
      #posts.to_json(:methods => :user, :include => {:replies => {:include => :user}}))
  end

  def latest
    head :unprocessable_entity unless max_id = params[:max_id]
    posts = get_posts.where {id > max_id}
    respond_with make_json_tree posts
  end

  def create
    post_params.delete('user_id')
    post_params.delete('reply')
    @post = current_user.posts.build(post_params.merge(:user => current_user))

    if @post.save
      respond_with @post
    else
      respond_with @post, :status => :unprocessable_entity
    end
  end

protected

  def get_posts
    Post.for_user(current_user).top_level.includes(:user, :post_attachments).includes(:replies => :user)
  end

  def make_json_tree posts
    posts.map do |post|
      post.attributes.merge(:user => post.user, :attachment => post.attachment, :replies => make_json_tree(post.replies))
    end
  end
    #post_lookup = Hash.new
    #posts = posts.each do |post|
      #post_lookup[post.id] = post
    #end.reject do |post|
      #if post.reply_id
        #post_lookup[post.reply_id].replies << post
        #true
      #else
        #false
      #end
    #end
  def post_params
    @post_params ||= params[:post] || {}
  end
end

app/views/posts/_header.html.erb
 <div class="header-wrapper">
<%= image_tag("machinelogo2.jpg", :alt => "camp",:class=>"logo") %>&nbsp;
<ul id="css3menu1" class="topmenu">
    <li class="topfirst"><%=link_to 'Home' home_url%></li>
    <li class="topmenu"><a href="#" title="Profile" style="height:18px;line-height:18px;"><span>Profile</span></a>
        <ul>
            <li><%=link_to 'Edit Profile', edit_home_url %></li>
            <li><%=link_to 'View profile', profile_home_url %></li>
        </ul>
    </li>
    <li class="toplast"><a href="#" title="Account" style="height:18px;line- height:18px;"><span>Account</span></a>
        <ul>
            <li><%=link_to 'Account settings',:controller=>"setting",:action=>"show"%></li>
            <li><%= link_to "Sign out", destroy_user_session_path %></li>
        </ul>
    </li>
</ul>            
	
	
<input type="text" class="searchfield" id="search" size="50"/>
<button type="button" class="searchbutton">Search</button>
</div>
<div class="headerline"></div>
<div style="clear:both;"></div>

app/views/posts/_post.html.erb
<%= button_to "I'm down",  {:controller=>"books",:action=>"new"},{:class=>"responsebutton"} %>
<%= button_to "I have it", {:controller=>"books",:action=>"new"},{:class=>"responsebutton"} %>
<%= button_to "I can help",{:controller=>"books",:action=>"new"},{:class=>"responsebutton"} %>

app/views/posts/_request.html.erb
<div class="inbox-wrapper">
<h2>Book reserve</h2>
<div class="inbox-divider"></div>
<div class="inbox-content">

<span>john</span><br/>
<span>wants to reserve</span><span>physics book</span>

<span><%=button_to'Deny',{:controller=>"books",:action=>"new"},{:class=>"denybutton"}%></span><span><%=button_to'Accept',{:controller=>"books",:action=>"new"},{:class=>"acceptbutton"}%></span>

</div>

</div>

app/views/posts/mypost.html.erb
<%=render 'leftsection'%>
<div id="center">
<div class="container">

</div>
</div>